import 'dart:developer' as dev;
import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';

const labelText = 'Email';
const hintText = '';

final Set<String> _validDomains = {
  'gmail.com',
  'yahoo.com',
  'hotmail.com',
  'aol.com',
  'hotmail.co.uk',
  'hotmail.fr',
  'msn.com',
  'yahoo.fr',
  'wanadoo.fr',
  'orange.fr',
  'comcast.net',
  'yahoo.co.uk',
  'yahoo.com.br',
  'yahoo.co.in',
  'live.com',
  'rediffmail.com',
  'free.fr',
  'gmx.de',
  'web.de',
  'yandex.ru',
  'ymail.com',
  'libero.it',
  'outlook.com',
  'uol.com.br',
  'bol.com.br',
  'mail.ru',
  'cox.net',
  'hotmail.it',
  'sbcglobal.net',
  'sfr.fr',
  'live.fr',
  'verizon.net',
  'live.co.uk',
  'googlemail.com',
  'yahoo.es',
  'ig.com.br',
  'live.nl',
  'bigpond.com',
  'terra.com.br',
  'yahoo.it',
  'neuf.fr',
  'yahoo.de',
  'alice.it',
  'rocketmail.com',
  'att.net',
  'laposte.net',
  'facebook.com',
  'bellsouth.net',
  'yahoo.in',
  'hotmail.es',
  'charter.net',
  'yahoo.ca',
  'yahoo.com.au',
  'rambler.ru',
  'hotmail.de',
  'tiscali.it',
  'shaw.ca',
  'yahoo.co.jp',
  'sky.com',
  'earthlink.net',
  'optonline.net',
  'freenet.de',
  't-online.de',
  'aliceadsl.fr',
  'virgilio.it',
  'home.nl',
  'qq.com',
  'telenet.be',
  'me.com',
  'yahoo.com.ar',
  'tiscali.co.uk',
  'yahoo.com.mx',
  'voila.fr',
  'gmx.net',
  'mail.com',
  'planet.nl',
  'tin.it',
  'live.it',
  'ntlworld.com',
  'arcor.de',
  'yahoo.co.id',
  'frontiernet.net',
  'hetnet.nl',
  'live.com.au',
  'yahoo.com.sg',
  'zonnet.nl',
  'club-internet.fr',
  'juno.com',
  'optusnet.com.au',
  'blueyonder.co.uk',
  'bluewin.ch',
  'skynet.be',
  'sympatico.ca',
  'windstream.net',
  'mac.com',
  'centurytel.net',
  'chello.nl',
  'live.ca',
  'aim.com',
  'bigpond.net.au',
  '163.com',
  '126.com',
  'sina.com',
  'foxmail.com',
  '139.com',
  'sohu.com'
};
final Set<String> _excludedDomains = {
  'avito.ru',
  'avito-boxberry.ru',
  'avito-dilivery.ru',
  'avito-office.ru',
  'avito-package.ru',
  'avito-payshops.ru',
  'avito-repayment.online',
  'avito-safe.online',
  'avito-save.online',
  'avitoguard.online',
  'avitosafe.online',
  'avitoexpress.online',
  'corona-virus-live.ru',
  '0815.ru',
  '0wnd.net',
  '0wnd.org',
  '10minutemail.co.za',
  '10minutemail.com',
  '123-m.com',
  '1fsdfdsfsdf.tk',
  '1pad.de',
  '20minutemail.com',
  '21cn.com',
  '2fdgdfgdfgdf.tk',
  '2prong.com',
  '30minutemail.com',
  '33mail.com',
  '3trtretgfrfe.tk',
  '4gfdsgfdgfd.tk',
  '4warding.com',
  '5ghgfhfghfgh.tk',
  '6hjgjhgkilkj.tk',
  '6paq.com',
  '7tags.com',
  '9ox.net',
  'a-bc.net',
  'agedmail.com',
  'ama-trade.de',
  'amilegit.com',
  'amiri.net',
  'amiriindustries.com',
  'anonmails.de',
  'anonymbox.com',
  'antichef.com',
  'antichef.net',
  'antireg.ru',
  'antispam.de',
  'antispammail.de',
  'armyspy.com',
  'artman-conception.com',
  'azmeil.tk',
  'baxomale.ht.cx',
  'beefmilk.com',
  'bigstring.com',
  'binkmail.com',
  'about-muesli.net',
  'bobmail.info',
  'bodhi.lawlita.com',
  'bofthew.com',
  'bootybay.de',
  'boun.cr',
  'bouncr.com',
  'breakthru.com',
  'brefmail.com',
  'bsnow.net',
  'bspamfree.org',
  'bugmenot.com',
  'bund.us',
  'burstmail.info',
  'buymoreplays.com',
  'byom.de',
  'c2.hu',
  'card.zp.ua',
  'casualdx.com',
  'cek.pm',
  'centermail.com',
  'centermail.net',
  'chammy.info',
  'childsavetrust.org',
  'chogmail.com',
  'choicemail1.com',
  'clixser.com',
  'cmail.net',
  'cmail.org',
  'coldemail.info',
  'cool.fr.nf',
  'courriel.fr.nf',
  'courrieltemporaire.com',
  'crapmail.org',
  'cust.in',
  'cuvox.de',
  'd3p.dk',
  'dacoolest.com',
  'dandikmail.com',
  'dayrep.com',
  'dcemail.com',
  'deadaddress.com',
  'deadspam.com',
  'delikkt.de',
  'despam.it',
  'despammed.com',
  'devnullmail.com',
  'dfgh.net',
  'digitalsanctuary.com',
  'dingbone.com',
  'disposableaddress.com',
  'disposableemailaddresses.com',
  'disposableinbox.com',
  'dispose.it',
  'dispostable.com',
  'dodgeit.com',
  'dodgit.com',
  'donemail.ru',
  'dontreg.com',
  'dontsendmespam.de',
  'drdrb.net',
  'dump-email.info',
  'dumpandjunk.com',
  'dumpyemail.com',
  'e-mail.com',
  'e-mail.org',
  'e4ward.com',
  'easytrashmail.com',
  'einmalmail.de',
  'einrot.com',
  'eintagsmail.de',
  'emailgo.de',
  'emailias.com',
  'emaillime.com',
  'emailsensei.com',
  'emailtemporanea.com',
  'emailtemporanea.net',
  'emailtemporar.ro',
  'emailtemporario.com.br',
  'emailthe.net',
  'emailtmp.com',
  'emailwarden.com',
  'emailx.at.hm',
  'emailxfer.com',
  'emeil.in',
  'emeil.ir',
  'emz.net',
  'ero-tube.org',
  'evopo.com',
  'example.com',
  'example.org',
  'example.net',
  'example.io',
  'explodemail.com',
  'express.net.ua',
  'eyepaste.com',
  'fakeinbox.com',
  'fakeinformation.com',
  'fansworldwide.de',
  'fantasymail.de',
  'fightallspam.com',
  'filzmail.com',
  'fivemail.de',
  'fleckens.hu',
  'frapmail.com',
  'friendlymail.co.uk',
  'fuckingduh.com',
  'fudgerub.com',
  'fyii.de',
  'garliclife.com',
  'gehensiemirnichtaufdensack.de',
  'get2mail.fr',
  'getairmail.com',
  'getmails.eu',
  'getonemail.com',
  'giantmail.de',
  'girlsundertheinfluence.com',
  'gishpuppy.com',
  'gmial.com',
  'goemailgo.com',
  'gotmail.net',
  'gotmail.org',
  'gotti.otherinbox.com',
  'great-host.in',
  'greensloth.com',
  'grr.la',
  'gsrv.co.uk',
  'guerillamail.biz',
  'guerillamail.com',
  'guerrillamail.biz',
  'guerrillamail.com',
  'guerrillamail.de',
  'guerrillamail.info',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamailblock.com',
  'gustr.com',
  'harakirimail.com',
  'hat-geld.de',
  'hatespam.org',
  'herp.in',
  'hidemail.de',
  'hidzz.com',
  'hmamail.com',
  'hopemail.biz',
  'ieh-mail.de',
  'ikbenspamvrij.nl',
  'imails.info',
  'inbax.tk',
  'inbox.si',
  'inboxalias.com',
  'inboxclean.com',
  'inboxclean.org',
  'infocom.zp.ua',
  'instant-mail.de',
  'ip6.li',
  'irish2me.com',
  'iwi.net',
  'jetable.com',
  'jetable.fr.nf',
  'jetable.net',
  'jetable.org',
  'jnxjn.com',
  'jourrapide.com',
  'jsrsolutions.com',
  'kasmail.com',
  'kaspop.com',
  'killmail.com',
  'killmail.net',
  'klassmaster.com',
  'klzlk.com',
  'koszmail.pl',
  'kurzepost.de',
  'lawlita.com',
  'letthemeatspam.com',
  'lhsdv.com',
  'lifebyfood.com',
  'link2mail.net',
  'litedrop.com',
  'lol.ovpn.to',
  'lolfreak.net',
  'lookugly.com',
  'lortemail.dk',
  'lr78.com',
  'lroid.com',
  'lukop.dk',
  'm21.cc',
  'mail-filter.com',
  'mail-temporaire.fr',
  'mail.by',
  'mail.mezimages.net',
  'mail.zp.ua',
  'mail1a.de',
  'mail21.cc',
  'mail2rss.org',
  'mail333.com',
  'mailbidon.com',
  'mailbiz.biz',
  'mailblocks.com',
  'mailbucket.org',
  'mailcat.biz',
  'mailcatch.com',
  'mailde.de',
  'mailde.info',
  'maildrop.cc',
  'maileimer.de',
  'mailexpire.com',
  'mailfa.tk',
  'mailforspam.com',
  'mailfreeonline.com',
  'mailguard.me',
  'mailin8r.com',
  'mailinater.com',
  'mailinator.com',
  'mailinator.net',
  'mailinator.org',
  'mailinator2.com',
  'mailincubator.com',
  'mailismagic.com',
  'mailme.lv',
  'mailme24.com',
  'mailmetrash.com',
  'mailmoat.com',
  'mailms.com',
  'mailnesia.com',
  'mailnull.com',
  'mailorg.org',
  'mailpick.biz',
  'mailrock.biz',
  'mailscrap.com',
  'mailshell.com',
  'mailsiphon.com',
  'mailtemp.info',
  'mailtome.de',
  'mailtothis.com',
  'mailtrash.net',
  'mailtv.net',
  'mailtv.tv',
  'mailzilla.com',
  'makemetheking.com',
  'manybrain.com',
  'mbx.cc',
  'mega.zik.dj',
  'meinspamschutz.de',
  'meltmail.com',
  'messagebeamer.de',
  'mezimages.net',
  'ministry-of-silly-walks.de',
  'mintemail.com',
  'misterpinball.de',
  'moncourrier.fr.nf',
  'monemail.fr.nf',
  'monmail.fr.nf',
  'monumentmail.com',
  'mt2009.com',
  'mt2014.com',
  'mycard.net.ua',
  'mycleaninbox.net',
  'mymail-in.net',
  'mypacks.net',
  'mypartyclip.de',
  'myphantomemail.com',
  'mysamp.de',
  'mytempemail.com',
  'mytempmail.com',
  'mytrashmail.com',
  'nabuma.com',
  'neomailbox.com',
  'nepwk.com',
  'nervmich.net',
  'nervtmich.net',
  'netmails.com',
  'netmails.net',
  'neverbox.com',
  'nice-4u.com',
  'nincsmail.hu',
  'nnh.com',
  'no-spam.ws',
  'noblepioneer.com',
  'nomail.pw',
  'nomail.xl.cx',
  'nomail2me.com',
  'nomorespamemails.com',
  'nospam.ze.tc',
  'nospam4.us',
  'nospamfor.us',
  'nospammail.net',
  'notmailinator.com',
  'nowhere.org',
  'nowmymail.com',
  'nurfuerspam.de',
  'nus.edu.sg',
  'objectmail.com',
  'obobbo.com',
  'odnorazovoe.ru',
  'oneoffemail.com',
  'onewaymail.com',
  'onlatedotcom.info',
  'online.ms',
  'opayq.com',
  'ordinaryamerican.net',
  'otherinbox.com',
  'ovpn.to',
  'owlpic.com',
  'pancakemail.com',
  'pcusers.otherinbox.com',
  'pjjkp.com',
  'plexolan.de',
  'poczta.onet.pl',
  'politikerclub.de',
  'poofy.org',
  'pookmail.com',
  'privacy.net',
  'privatdemail.net',
  'proxymail.eu',
  'prtnx.com',
  'putthisinyourspamdatabase.com',
  'qq.com',
  'quickinbox.com',
  'rcpt.at',
  'reallymymail.com',
  'realtyalerts.ca',
  'recode.me',
  'recursor.net',
  'reliable-mail.com',
  'rhyta.com',
  'rmqkr.net',
  'royal.net',
  'rtrtr.com',
  's0ny.net',
  'safe-mail.net',
  'safersignup.de',
  'safetymail.info',
  'safetypost.de',
  'saynotospams.com',
  'schafmail.de',
  'schrott-email.de',
  'secretemail.de',
  'secure-mail.biz',
  'senseless-entertainment.com',
  'services391.com',
  'sharklasers.com',
  'shieldemail.com',
  'shiftmail.com',
  'shitmail.me',
  'shitware.nl',
  'shmeriously.com',
  'shortmail.net',
  'sibmail.com',
  'sinnlos-mail.de',
  'slapsfromlastnight.com',
  'slaskpost.se',
  'smashmail.de',
  'smellfear.com',
  'snakemail.com',
  'sneakemail.com',
  'sneakmail.de',
  'snkmail.com',
  'sofimail.com',
  'solvemail.info',
  'sogetthis.com',
  'soodonims.com',
  'spam4.me',
  'spamail.de',
  'spamarrest.com',
  'spambob.net',
  'spambog.ru',
  'spambox.us',
  'spamcannon.com',
  'spamcannon.net',
  'spamcon.org',
  'spamcorptastic.com',
  'spamcowboy.com',
  'spamcowboy.net',
  'spamcowboy.org',
  'spamday.com',
  'spamex.com',
  'spamfree.eu',
  'spamfree24.com',
  'spamfree24.de',
  'spamfree24.org',
  'spamgoes.in',
  'spamgourmet.com',
  'spamgourmet.net',
  'spamgourmet.org',
  'spamherelots.com',
  'spamhereplease.com',
  'spamhole.com',
  'spamify.com',
  'spaml.de',
  'spammotel.com',
  'spamobox.com',
  'spamslicer.com',
  'spamspot.com',
  'spamthis.co.uk',
  'spamtroll.net',
  'speed.1s.fr',
  'spoofmail.de',
  'stuffmail.de',
  'super-auswahl.de',
  'supergreatmail.com',
  'supermailer.jp',
  'superrito.com',
  'superstachel.de',
  'suremail.info',
  'talkinator.com',
  'teewars.org',
  'teleworm.com',
  'teleworm.us',
  'temp-mail.org',
  'temp-mail.ru',
  'tempe-mail.com',
  'tempemail.co.za',
  'tempemail.com',
  'tempemail.net',
  'tempinbox.co.uk',
  'tempinbox.com',
  'tempmail.eu',
  'tempmaildemo.com',
  'tempmailer.com',
  'tempmailer.de',
  'tempomail.fr',
  'temporaryemail.net',
  'temporaryforwarding.com',
  'temporaryinbox.com',
  'temporarymailaddress.com',
  'tempthe.net',
  'thankyou2010.com',
  'thc.st',
  'thelimestones.com',
  'thisisnotmyrealemail.com',
  'thismail.net',
  'throwawayemailaddress.com',
  'tilien.com',
  'tittbit.in',
  'tizi.com',
  'tmailinator.com',
  'toomail.biz',
  'topranklist.de',
  'tradermail.info',
  'trash-mail.at',
  'trash-mail.com',
  'trash-mail.de',
  'trash2009.com',
  'trashdevil.com',
  'trashemail.de',
  'trashmail.at',
  'trashmail.com',
  'trashmail.de',
  'trashmail.me',
  'trashmail.net',
  'trashmail.org',
  'trashymail.com',
  'trialmail.de',
  'trillianpro.com',
  'twinmail.de',
  'tyldd.com',
  'uggsrock.com',
  'umail.net',
  'uroid.com',
  'us.af',
  'venompen.com',
  'veryrealemail.com',
  'viditag.com',
  'viralplays.com',
  'vpn.st',
  'vsimcard.com',
  'vubby.com',
  'wasteland.rfc822.org',
  'webemail.me',
  'weg-werf-email.de',
  'wegwerf-emails.de',
  'wegwerfadresse.de',
  'wegwerfemail.com',
  'wegwerfemail.de',
  'wegwerfmail.de',
  'wegwerfmail.info',
  'wegwerfmail.net',
  'wegwerfmail.org',
  'wh4f.org',
  'whyspam.me',
  'willhackforfood.biz',
  'willselfdestruct.com',
  'winemaven.info',
  'wronghead.com',
  'www.e4ward.com',
  'www.mailinator.com',
  'wwwnew.eu',
  'x.ip6.li',
  'xagloo.com',
  'xemaps.com',
  'xents.com',
  'xmaily.com',
  'xoxy.net',
  'yep.it',
  'yogamaven.com',
  'yopmail.com',
  'yopmail.fr',
  'yopmail.net',
  'yourdomain.com',
  'yuurok.com',
  'z1p.biz',
  'za.com',
  'zehnminuten.de',
  'zehnminutenmail.de',
  'zippymail.info',
  'zoemail.net',
  'zomg.info'
};
// final RegExp _emailRegExp = RegExp(
//    r"^(([^<>()\[\]\\.,;:\s@']+(\.[^<>()\[\]\\.,;:\s@']+)*)|('.+'))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$");
final RegExp _emailRegExp = RegExp(
    r"^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,253}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,253}[a-zA-Z0-9])?)*$");
final RegExp _nonASCIIRegExp = RegExp('[^\x00-\x7F]');
final RegExp _firstDomainCharRegExp = RegExp('[^a-zA-Z0-9]');
const int _minLength = 8;
const int _maxLength = 255;

const String invalidEmailMessage01 = 'Email can\'t be null';
const String invalidEmailMessage02 = 'Email can\'t be empty';
const String invalidEmailMessage03 =
    'Email must have at least $_minLength characters';
const invalidEmailMessage04 = 'Email must have at most $_maxLength characters';
const String invalidEmailMessage05 = 'Non ASCII characters found';
const String invalidEmailMessage06 = 'Not an email address - wrong parts';
const String invalidEmailMessage07 = 'Incorrectly formatted email address';
const String invalidEmailMessage08 = 'Not an email address - first domain char';
const String invalidEmailMessage09 = 'Not an email address - excluded domain';
const String invalidEmailMessage10 =
    'Not an email address - not a valid domain';

class EmailField extends HookWidget {
  const EmailField({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final _emailFieldKey = GlobalKey<FormFieldState>();

    return Focus(
      child: TextFormField(
        key: _emailFieldKey,
        validator: _validateEmail,
        autofillHints: const [AutofillHints.email],
        decoration: const InputDecoration(
          labelText: labelText,
          // An empty helperText prevents field from changing height
          // when an error is shown:
          helperText: '',
          hintText: hintText,
          prefixIcon: Icon(Icons.email),
        ),
      ),
      onFocusChange: (hasFocus) {
        if (hasFocus) {
          dev.log('focus: yes');
        } else {
          dev.log('focus: no');
          _emailFieldKey.currentState!.validate();
        }
      },
    );
  }
}

/// If genericResponse is supplied as a non empty string, it becomes the
/// only error report ever returned and replaces all other errors.
String? _validateEmail(String? email, [String? genericResponse]) {
  if (email == null) {
    return genericResponse ?? invalidEmailMessage01;
  }
  if (email.isEmpty) {
    return genericResponse ?? invalidEmailMessage02;
  } else {
    final length = email.length;
    if (length < _minLength) {
      return genericResponse ?? invalidEmailMessage03;
    }

    if (length > _maxLength) {
      return genericResponse ?? invalidEmailMessage04;
    }

    if (_nonASCIIRegExp.hasMatch(email)) {
      return genericResponse ?? invalidEmailMessage05;
    }

    final emailParts = email.split('@');
    if (emailParts.length != 2) {
      return genericResponse ?? invalidEmailMessage06;
    }

    final addr = emailParts[0];
    final domain = emailParts[1].toLowerCase();
    if (addr.contains('"') || addr.contains("'")) {
      return genericResponse ?? invalidEmailMessage07;
    }

    if (!_emailRegExp.hasMatch(email)) {
      return genericResponse ?? invalidEmailMessage07;
    }

    final firstDomainCharMatches = _firstDomainCharRegExp.allMatches(domain[0]);
    if (firstDomainCharMatches.isNotEmpty) {
      return genericResponse ?? invalidEmailMessage08;
    }

    if (_excludedDomains.contains(domain)) {
      return genericResponse ?? invalidEmailMessage09;
    }

    if (!_validDomains.contains(domain)) {
      return genericResponse ?? invalidEmailMessage10;
    }
  }
  return null;
}
